CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID INTEGER PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT,
    PLATFORM TEXT,
    STORE TEXT,
    URL TEXT,
    UPDATE_DATE DATE
);
\
CREATE TABLE IF NOT EXISTS PRODUCT_RECORDS (
    PRODUCT_ID INTEGER PRIMARY KEY,
    PRICE NUMBER,
    CUOTAS INTEGER,
    CURRENCY TEXT,
    RANK INTEGER,
    RATING NUMBER,
    RATE_COUNT INTEGER,
    MOST_SELLED INTEGER,
    PROMOTED INTEGER,
    UPDATE_DATE DATE
);
