CREATE TABLE IF NOT EXISTS NEWS (
    NEW_ID INTEGER PRIMARY KEY,
    TITLE TEXT,
    TOPIC_ID INTEGER,
    NEWSPAPER_ID INTEGER,
    URL TEXT,
    PUBLISH_DATE DATE,
    ANTIQUE TEXT,
    UPDATE_DATE DATE
);
\
CREATE TABLE IF NOT EXISTS TOPICS (
    TOPIC_ID INTEGER PRIMARY KEY,
    TOPIC TEXT,
    TOPIC_NEWS INTEGER,
    UPDATE_DATE DATE
);
\
CREATE TABLE IF NOT EXISTS NEWSPAPERS (
    NEWSPAPER_ID INTEGER PRIMARY KEY,
    NEWSPAPER TEXT,
    NEWS_COUNT INTEGER,
    UPDATE_DATE DATE
);